{"name": "test_login[账号错误，登录失败]", "status": "passed", "attachments": [{"name": "stdout", "source": "324060ef-fa76-4bb3-850a-23b61c070457-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'admin1'"}, {"name": "password", "value": "'123456'"}, {"name": "expect", "value": "{'code': 801, 'message': '用户名或者密码错误'}"}], "start": 1648190889981, "stop": 1648190890000, "uuid": "63b8d0ed-c244-4bde-96ec-bc7258b5866b", "historyId": "c1196bf02ec58dedc389c972dde73ad9", "testCaseId": "8bd8079eaae40b2d729c0d112c307024", "fullName": "case.test_login#test_login", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "PC-20200806UOAU"}, {"name": "thread", "value": "78776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_login"}]}